// We require the Hardhat Runtime Environment explicitly here. This is optional
// but useful for running the script in a standalone fashion through `node <script>`.
//
// When running the script with `npx hardhat run <script>` you'll find the Hardhat
// Runtime Environment's members available in the global scope.
import { spawn } from "child_process";
import { ethers } from "hardhat";

// Traits deployed to: 0x502A32eAaa4bb3Ce5fDC0A5A31810a02ec5bCaf6
// HouseTraits deployed to: 0xBe6826fE629caFB3C54623aF1A0cf514A2403010
// Habitat deployed to: 0x996863a1d07838793A1CB29C6d18715BC956d370
// RandomGenerator deployed to: 0x69D65EA814AAB02A3501F43028eC6A28cFD05425
// CnM deployed to: 0xa6AC8E8F8b8A1f78Fd16DA4D6aAD2aFE5dFD058D
// House deployed to: 0x0507f38951C8FCF10E74D3F23CaBFc886138FeD2
// CHEDDAR deployed to: 0x95F62926c2335ADbB97F4C59253b16c45b253e6B
// CnMGame deployed to: 0x1099f942eE92156c2F29e8aCdD777Ac22e95Adb5
// HouseGame deployed to: 0x8451453aBB5ACDBF63Db821668A070F14787d7Fe

const CONTRACT_ADDR_TRAIT = "0xcc010eb2d98ad76ab2f0a253f97a9c4d3042e5a1";
const CONTRACT_ADDR_HOUSE_TRAIT = "0xBe6826fE629caFB3C54623aF1A0cf514A2403010";

const getInstance = async (name: string, address: string) => {
  // Set up an ethers contract, representing our deployed Box instance
  const Contract = await ethers.getContractFactory(name);
  const instance = await Contract.attach(address);

  return instance;
};

async function upload() {
  const trait = await getInstance("Traits", CONTRACT_ADDR_TRAIT);
  const houseTrait = await getInstance(
    "HouseTraits",
    CONTRACT_ADDR_HOUSE_TRAIT
  );

  await trait.uploadTraits(
    1,
    [0, 1, 2, 3, 4],
    [
      {
        name: "Orange Stripes",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAG1BMVEVHcEz7oDbnhxjibRPSbxj6iyr////IVxP9fHxIyv6fAAAAAXRSTlMAQObYZgAAAT5JREFUeAGV07de80AMAPD0rE6dYznx/H2nB6Ddj5U+02c6zLw5smRdSxck0elvyb2xIRBX19uI/9YB7g+rZ8VwLh9pMeDq3Rv5cBhADwv5cAB6uBRws2arwUAA540bONdZhR5WN4YCFZqQZ40BZO5MdNQA8kGTvhRAYRgDhDC5GQBkS5APCAYBtA0fwGDAMHBQoJx+k4oX9JF6CwBNwZdyUEfmAIrK/g80HMiwUutTBQOFIVg8X3D95lkBGAwMKH5lHw6qeaAddwocBkqoD6rnQCPXYxJIYx24+8mruT1OGgQsBUgcpnAoM+cRzAjqmXYFVC3zAFoMhynIS9X/eZXeTgKyJpAt/ChZI+JyhxXo/3ymcMijJPGjaG3vqk0kcQANWnOvnJGHsmNP64yS8NQbPc04cXCXZDrrIc3Wxh+ac1ZILpWFRQAAAABJRU5ErkJggg==",
      },
      {
        name: "Orange",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAElBMVEVHcEz7oDbSbxjnhxj////9fHyqDprAAAAAAXRSTlMAQObYZgAAAOJJREFUeAGt09dxw0AMBFCmAg4jF3AD+19h9e9UgftvxgQPYMAFx1Va8c0lha4RoHx9BC41wM+hPNcRgj78XD2lx5IDXOVRgJOCO0kTQkcI+m6DvgqoAOFKPeGawakFREDI4EqSHeiWSWOQIrtSsANq3IgNcCWLgztpHvyIV4VXB5CLH4U1YCNe/BrQTU0ObF/bF+VSge37hOTGj25AAp6DlOghjmnoAS4z6JxcgFEG7GBcIJZh4JjGDv8AbMAeokF0wC/SUtn92fQgeqIN7gM/aZOy/+NO1qRs8OKbzvXuWj2ff7lU8EEwF5oAAAAASUVORK5CYII=",
      },
      {
        name: "Gray Stripes",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAHlBMVEVHcEx4eHixsbGQkJB0dHSgoKCEhIT///9bW1v9fHxuoUG5AAAAAXRSTlMAQObYZgAAAUZJREFUeAGV0zdXw0AMAODUl4yI+wN5qWsOmeeRljLS2Wle6TO9zPxi7iTrGl2QRKfPknvlhwD4ul4FWPgO4P/w9awYtvjDLQpdvblPHw6F4OGUPhwIHg4Y3Kzx16AwgK3KfrEls7QcVjMGDQK14qhT6RYddyYyqlscdWvmSwAFhjFgCIP9biGzAjjqGugGUFV0AN0uQdeBBj79minumA/X64igNCi0HRwdB6itLXYlHPCwXOojAYVaGVi+2aH6/o0AEii01Xe3DwY7D6XjXIBCYY7lQbUEXCzJMTGk8R24+0mrbLKRNDBMTCDHagqrPDOLYGygnDn5AmxLFkCdYDUFfqnab3fc20iA1wZ4Cz+K1wDwuWPC0H57SmGVRnHiR5n15NxuwokDrJg19fIZecgbk3mZmSQ89UpLMkocnCeZzLoKsp/jA98+aAcN3hFsAAAAAElFTkSuQmCC",
      },
      {
        name: "Gray",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAFVBMVEVHcEyxsbGQkJB0dHSEhIT////9fHyywF5qAAAAAXRSTlMAQObYZgAAAOpJREFUeAGt08dyhDAMBuCtd9PuRAx3TzS5p/hOeYO8/0vExhJFLmn7b9P4c13glAlAvP0C0KYAfg/xuY6g6CPnOhf+s+QAb/4TQE0gT5IDdSqMWudiOCfBJKAwb8XZfgVQ56AojFEBvBUuO6AtFxQGH7crAj4gRY5YAZ4KjoCe2xs5YiKYBIBr/IysATxilGsAbeougPe1XiiZOOyuJ7h0+CwGeEAbatcStJ+zO0BrgebECLgh3Q4uC+g4XFH7sdcHADKgBM2gBeDoKl/sHjY6CJ1og/6KL1S5Yv/g3rmyxQ5GWdFcs6yS+QK7HEeMi24fbwAAAABJRU5ErkJggg==",
      },
      {
        name: "Black",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAElBMVEVHcEwpKSkcHBwQEBD////9fHxPR57PAAAAAXRSTlMAQObYZgAAAOJJREFUeAGt0+d1wzAMBGC1AQS/DGBePABfkP8uG2T/ZWKIgApYUs/trO+xuXSNAOXrA3CuAX4O5bmOMOvDz9VTeiw5QJBHAU4K7iRNmDvCrO826KuAChAC9YSQwakFRMCcQSDJDnTLpDFIkV0p2AE1bsQGCGRxcCHNix9xV7g7gFz8KKwBG3Hza0A3NTmwfW1flEsFtu8Tkld+cwMS8DNIiR7ikIYe4PwEnZMLMMiAHQwLxDKMHNPY8R+ADdhDNIgO+CYtld2fTQ+iJ9rgMvK7Nin7P+5kTcoGN990rodr9XwCGgxDTDhCJYIAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    2,
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [
      {
        name: "Wide Green",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcExcukgcHBz///9kd+lxAAAAAXRSTlMAQObYZgAAACNJREFUeAFjgINRwDqBcQqcYzuFdS+cIzqFdSoGB6GHaDAKAENPBm4mIRAiAAAAAElFTkSuQmCC",
      },
      {
        name: "Wide Blue",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcEx0y9McHBz////Qa3oCAAAAAXRSTlMAQObYZgAAACNJREFUeAFjgINRwDqBcQqcYzuFdS+cIzqFdSoGB6GHaDAKAENPBm4mIRAiAAAAAElFTkSuQmCC",
      },
      {
        name: "Unamused",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcEz6sxscHBz////+u/oWAAAAAXRSTlMAQObYZgAAACFJREFUeAFjwA5Gge0U1r1wjugU1qnYOawTGKcQb+goAACnFwVEkLGYvQAAAABJRU5ErkJggg==",
      },
      {
        name: "Shades",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAACVBMVEVHcEwAAAD///8W1S+BAAAAAXRSTlMAQObYZgAAAClJREFUeAFjwApGAWNaiORUBxgncmpYKozDEJYiOhOuTjSANYR4U0cBAEjyBboIrLXgAAAAAElFTkSuQmCC",
      },
      {
        name: "Sad",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAACVBMVEVHcEx0y9McHBzLttL/AAAAAXRSTlMAQObYZgAAACFJREFUeAFjwA5GAeMUxhQ4R3QKY6oDjMM6gSGVTENHAQAwxANEz4gN2AAAAABJRU5ErkJggg==",
      },
      {
        name: "Mean",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcEz6sxscHBz////+u/oWAAAAAXRSTlMAQObYZgAAACdJREFUeAFjGNmABYRgwLaBYSucIzqBcSqCM4UVwWGdwDiFTOtGAQC+oAUjUvZJqwAAAABJRU5ErkJggg==",
      },
      {
        name: "Happy Green",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcExcukgcHBz///9kd+lxAAAAAXRSTlMAQObYZgAAACVJREFUeAFjgINRwDqBcQqcYzuFdS+cIzqFdSpC3RTWBjJtGAUAr9wFGn/CckkAAAAASUVORK5CYII=",
      },
      {
        name: "Happy Blue",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcEx0y9McHBz////Qa3oCAAAAAXRSTlMAQObYZgAAACVJREFUeAFjgINRwDqBcQqcYzuFdS+cIzqFdSpC3RTWBjJtGAUAr9wFGn/CckkAAAAASUVORK5CYII=",
      },
      {
        name: "Cute",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAADFBMVEVHcEwcHBxcukj///+1DTF2AAAAAXRSTlMAQObYZgAAACRJREFUeAFjGNmAN4A5BM6xjeAPg3NUIzhxcLgWMK0g07pRAABBCAS7xw+OGgAAAABJRU5ErkJggg==",
      },
      {
        name: "Blushing Mean",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAD1BMVEVHcEz6sxvzR0ccHBz///+iy2UdAAAAAXRSTlMAQObYZgAAAD1JREFUeAFjGClgFAhASXTA4mgAJE0EMSQYBQ2BhCFWCQEGQSwSDBAdAsQ7iomJCUKgAwUFBQiBAKNgFAAAHooDV5GX1iIAAAAASUVORK5CYII=",
      },
      {
        name: "Blushing Happy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAD1BMVEVHcExcukjzR0ccHBz///8cbncrAAAAAXRSTlMAQObYZgAAADxJREFUeAFjGPFgFAgaMjAwGgpgiLM4AgUFTRwxJBgFQRKGgljMAkkYkGA3ExMThEAHCgoKEAIBRsEoAACItwOF5YQ9ugAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    9,
    [0, 1, 2],
    [
      {
        name: "Mustache",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcExsTzX/tSH8AAAAAXRSTlMAQObYZgAAACJJREFUeAFjGILgewOI5Px+AkTxf//BDKJTwCTzwQcD6zYAEUkHTNmSrisAAAAASUVORK5CYII=",
      },
      {
        name: "Happy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABJJREFUeAFjGLpAC0KJDCpHAQAk2gA/cLc1YAAAAABJRU5ErkJggg==",
      },
      {
        name: "Default",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABJJREFUeAFjGLqAA0KJDCpHAQAREAAd5fGtwwAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    8,
    [0, 1, 2],
    [
      {
        name: "Muzzle and Stomach",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAACVJREFUeAFjGBKgHkJ9bwBT/1GoehiBEHp4AMKFUgkQSoEeLgUAqucKUxYWuGAAAAAASUVORK5CYII=",
      },
      {
        name: "Everywhere",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAAFxJREFUeAFjgAJ+CCXfAKEOoFAPIEqAVEMDA3sDA+PBAwxMDAyMjg4gcSZUKlkBRLFBKBYQRTmoh1DfIa77j0LVQwiokA2IenigDsw98A9MJfwBUwo/IIoKGGgIABrkGPHN2MulAAAAAElFTkSuQmCC",
      },
      {
        name: "Chest and Tail Tip",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAADBJREFUeAFjgAJ+CCXfAKEOoFAPIEogFDtECRPDoAQ2EKoOQv2DUH8g1A8IVUBL+wGH8AkA/Lxg0AAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    11,
    [0, 1, 2, 3, 4, 5, 6],
    [
      {
        name: "Wings",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAAEBJREFUeAFjIB2wQCg+BgMQJc/wAUwxQqhGCHUQQj2AUgUgiv8DmMf+E0wx/wVTDDYQyq4ATNkbgCl5mBVDDgAA4IARZVHGQh8AAAAASUVORK5CYII=",
      },
      {
        name: "Hat",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwBAMAAAClLOS0AAAAD1BMVEVHcExsTzWffV/6sxv6zWLDt9qHAAAAAXRSTlMAQObYZgAAACtJREFUeAFjgIFRwCgoKIhdQpFkCSWcEoqCpFnO7GxsjEMDSMtIAqNgFAAARmYCjaJ/mf0AAAAASUVORK5CYII=",
      },
      {
        name: "Eyebrows",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAABVJREFUeAFjGHjQ0ACmHCE8JYYhDQAZgwFk4ImNrwAAAABJRU5ErkJggg==",
      },
      {
        name: "Earrings",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAQMAAABtzGvEAAAABlBMVEVHcEz6sxti9EbAAAAAAXRSTlMAQObYZgAAABxJREFUeAFjoBrggVCCEIoPRU4CQilCKDmG4QsAeRIAg6STi2QAAAAASUVORK5CYII=",
      },
      {
        name: "Dollar Chain",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAACVBMVEVHcEz6oxv6zWJ3RllFAAAAAXRSTlMAQObYZgAAAD9JREFUeAFjoBEYBQnIHAEGBhY4RwKEYIAVWSVTApMDQpNYKpIJjBOQOCwdSByOBlzKGFCUtaAYgFNPA01DBQDPNQcQtxnJRQAAAABJRU5ErkJggg==",
      },
      {
        name: "Chain",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAACVBMVEVHcEz6oxv6zWJ3RllFAAAAAXRSTlMAQObYZgAAACdJREFUeAFjoBEYBQnIHAEGBhY4RwKEYIAVWSVTApMDQpNY6vALFQAAtAIpTRXEkAAAAABJRU5ErkJggg==",
      },
      {
        name: "Bandana",
        png: "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwAgMAAAAqbBEUAAAACVBMVEVHcEx0y9M/s7+X/XgyAAAAAXRSTlMAQObYZgAAADZJREFUeAFjoBEYBQrIHA0GBg44h2vVqhVwDmNoaABCXWioA4IjGopkAmsIEocxANlwhyEUKgAIGAWQWVVZrQAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    13,
    [0, 1],
    [
      {
        name: "Light",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURQAAAPyhWPx6SP3He1VDM/+YcLLNodQAAAABdFJOUwBA5thmAAAAm0lEQVQ4y+3UzQ3DIAwFYNiAFzpAsJIBGCFSJ+j+wzQQyI+x2xxyiKr64MunZ0UBY8y/riykcgJYQLEqgmErNdTQTtjEfYjFjuS0eafJ/hDhAzn2N4hS7+ZOjDrKNr4CUd9SSJ2RXVMDQaJQvuJA9VQi4JUDKyTdgDi1tMQ8Hs856UTKQ6U7GnOT9sR/2wdtveQFM2qozLzdW/EGCWQhQAoLzh0AAAAASUVORK5CYII=",
      },
      {
        name: "Dark",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURQAAAI5dP7ZfRaJvT1VDM6t9YCl7Tq8AAAABdFJOUwBA5thmAAAAm0lEQVQ4y+3UzQ2AIAwGUNiAigNoNyDoACZu4P67iIh/pVUPHoyxB2Ly8jUEqEr99WTBVIYBDSDYIozBVmIoo52QjvsQiR3JSP1uk/4QwQkZchqI02p9+CJUYLR2cIhVTnUIeUJ6TTUeOKrTLg603IoL+xAuLBH3AlyX0xyzUPYhaViKTbk36uLCzYm9mgdpvPgBU2Io9Xzdv2IEElwhx6r8kfoAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    16,
    [0, 1, 2],
    [
      {
        name: "Unamused",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AQMAAAD/tomoAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURQAAAFVDM6uUKEQAAAABdFJOUwBA5thmAAAAEklEQVQY02NgGLKA8QAPw7AHALgpAM46pbaPAAAAAElFTkSuQmCC",
      },
      {
        name: "Happy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AQMAAAD/tomoAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURQAAAFVDM6uUKEQAAAABdFJOUwBA5thmAAAAFklEQVQY02NgGLrgAAuYYlTgYhi2AADVFwDwyyTJigAAAABJRU5ErkJggg==",
      },
      {
        name: "Angry",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJUExURQAAAFVDM1VDMywelNkAAAACdFJOUwD+LJYSIwAAAB9JREFUKM9jYBgFVAEKYAQDHAwMDggeEwPjaADRFwAA1hcAjO7F3SgAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    15,
    [0, 1],
    [
      {
        name: "Squint",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AQMAAAD/tomoAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURQAAAFVDM6uUKEQAAAABdFJOUwBA5thmAAAAHUlEQVQY02NgGLaAkYEJwjjAgyohwAGhFVgGvycAwNMBDB2nCGsAAAAASUVORK5CYII=",
      },
      {
        name: "Cute",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AQMAAAD/tomoAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAGUExURQAAAFVDM6uUKEQAAAABdFJOUwBA5thmAAAAH0lEQVQY02NgGH7gAA+YYjzAh8KHAwEOCK3AMvj9AgD/igKkc5graAAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    18,
    [0, 1, 2],
    [
      {
        name: "Square",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJUExURQAAAP///4JrVpV2CjIAAAACdFJOUwBpQv0UxAAAAEBJREFUKM9jYBgFSIBp1aoGhlUroDzO0NAEptAwKE81NDQCKNJAT14nMi9KE0WOAZUniocH9wPIRwj/gX07PAEA69spj9OIqhUAAAAASUVORK5CYII=",
      },
      {
        name: "Half Moon",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJUExURQAAAP///4JrVpV2CjIAAAACdFJOUwBpQv0UxAAAAERJREFUKM9jYBgFdAVcq1YtYFq1CspTDQ2N4AwNbcDF60TmRWmiyDGEhkFNAepJYBCNgPKYQKq0FsAsXBqFYv2CkRHMAFGLFFAW5DoZAAAAAElFTkSuQmCC",
      },
      {
        name: "Circle",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAJUExURQAAAP///4JrVpV2CjIAAAACdFJOUwBpQv0UxAAAAFhJREFUKM9jYBgFyEBrBRA3wHhTw4A4AcphCg1tYAqNgPI4Q0MTOEPDoDzV0NAIdF5oA+W8TmRelCaKHAMqTzQMyWUMohFIrmbQWgDz0dIoZN9yLRiu8QgAeyMi9HC5mxwAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    19,
    [0, 1, 2, 3, 4, 5, 6, 7],
    [
      {
        name: "Purple Frizzy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1sDAwLSSxqR6uYexiqIAAAABdFJOUwBA5thmAAABfklEQVQ4y3WUC5LDIAiG0ROI6QECswfojHuBTr3/mZaHyYq2TJo0fv6IgAFkqogsJg+xArfJKFbBF4IJCSMdq7SIAC9zBJ8QHk3t+QG1Yc8NtbaxjbQW0TGj54yO3977JjPU1d6rTMnjO+qO0NNyXB5vEV0Zw9pOgFRuxJpMHdeLRWIqJZLBkWW96imigV6E9c6yTnNUe0ceiZfUi5i8Olh/+kvnyahXhfW/IX6YiNHC1VJm9SDPio+X+5+bgnQKScgyyV+GiftTVWzxMgZkDmVJst1OTTHCsGWk2+Z+yR697Z8XxLaNz4i+Ix7I1ioRjeSwlqouiDxvTDF4RewIWTye88bYVrci8b4Yj8bhkCiN3lAy1XdEASU9pu5QtxHOo57iWxTPY9UtgwUYj2oaVRJXvB19K5PM0F/8YFg/GoLli2FTB0q7R0fF2fLJ8By6DwgxVrJHGbcQvU1NhqK/7N2c7CWISnYvelv8Qf4fWFSQT5wWntNR8tQPafF4wh8tc1GSDMUVRwAAAABJRU5ErkJggg==",
      },
      {
        name: "Purple Bun",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1rSSxsDAwKeAvDVZFrsAAAABdFJOUwBA5thmAAAAwUlEQVQ4y+3S4Q2EIAwFYNiAJzfAHRtcmMAL+89kLUofoMkN4PthjF9aKOJQ8wVizvJ0FlAGY0p7Phe0pJr3RKekRBStW1dWd8dClPt21hFRi8pvLsM+C16lyLZ13aWVRaUipJuJ2rySnoAUFTsxLCfVfisRwmG1H2byWYtwSyv6ENlH3xMXjWQS3H8kZ7jy+p4og4uI3PEn0eYhqlMaeaJhUrFwvgwinyYKjcbrZte2kR+lv/buJt5Wme2enjy5yAY6lDFoIV2Q+QAAAABJRU5ErkJggg==",
      },
      {
        name: "Pink Frizzy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1sDAwP+ejv+JdbTUEGoAAAABdFJOUwBA5thmAAABfklEQVQ4y3WUC5LDIAiG0ROI6QECswfojHuBTr3/mZaHyYq2TJo0fv6IgAFkqogsJg+xArfJKFbBF4IJCSMdq7SIAC9zBJ8QHk3t+QG1Yc8NtbaxjbQW0TGj54yO3977JjPU1d6rTMnjO+qO0NNyXB5vEV0Zw9pOgFRuxJpMHdeLRWIqJZLBkWW96imigV6E9c6yTnNUe0ceiZfUi5i8Olh/+kvnyahXhfW/IX6YiNHC1VJm9SDPio+X+5+bgnQKScgyyV+GiftTVWzxMgZkDmVJst1OTTHCsGWk2+Z+yR697Z8XxLaNz4i+Ix7I1ioRjeSwlqouiDxvTDF4RewIWTye88bYVrci8b4Yj8bhkCiN3lAy1XdEASU9pu5QtxHOo57iWxTPY9UtgwUYj2oaVRJXvB19K5PM0F/8YFg/GoLli2FTB0q7R0fF2fLJ8By6DwgxVrJHGbcQvU1NhqK/7N2c7CWISnYvelv8Qf4fWFSQT5wWntNR8tQPafF4wh8tc1GSDMUVRwAAAABJRU5ErkJggg==",
      },
      {
        name: "Pink Bun",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1v+ejsDAwP+Oe7D5oKUAAAABdFJOUwBA5thmAAAAwUlEQVQ4y+3S4Q2EIAwFYNiAJzfAHRtcmMAL+89kLUofoMkN4PthjF9aKOJQ8wVizvJ0FlAGY0p7Phe0pJr3RKekRBStW1dWd8dClPt21hFRi8pvLsM+C16lyLZ13aWVRaUipJuJ2rySnoAUFTsxLCfVfisRwmG1H2byWYtwSyv6ENlH3xMXjWQS3H8kZ7jy+p4og4uI3PEn0eYhqlMaeaJhUrFwvgwinyYKjcbrZte2kR+lv/buJt5Wme2enjy5yAY6lDFoIV2Q+QAAAABJRU5ErkJggg==",
      },
      {
        name: "Headphones Frizzy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURQAAANbW1v+ejsDAwP////+JdZiryjcAAAABdFJOUwBA5thmAAABmElEQVQ4y3WTbZKDMAiGcb2AaWb/d9D+N6V7AZu9wM54/6vsC1hNUsu0fvCEN0CQgqQYAjMLbrAL85XcgkiIwhOPjpiXHYGlC+dlTB40Lbwjc+SFkwflXCFzuE0tmnaExxbxblOJsBWXVqHf9RO6revfOeK1RtcD3T4jEN0L7dy6uKNvC0raMSsl8kzUDS/EozZT/foThFiUBqG5HmMozgjaEOT8TEJM+hNHEWjUdzNCsD4qij/Qwzp4DZHosyFhvq046GDpwkO9KuAetcaH6tFuyEiX3O0ctpfNII/K6KJofEqokAnyCx2EtjRwwAs2SwWh3rPHwDzfkFgZ5yh9RlKioUZyIIkNSgcKDYIDyd8VpbksTMP2kt82E/o6aZRm/0IPOUOqKBkJlajDVwxEOWcto0T2FWMFpkP8WA8UtWQdiCihQp3NpM2DN7oIMiFdof9qL59HQ/7VVoIhbKh7V3Q0OKOaJbu6BlU5xmS3YbtU2dvSzlCt1/s0d/ZSBQ29q+il0aP+cDRR1M+h2Lhsx9AX89A1ijP9A8zgZ9xp1s1JAAAAAElFTkSuQmCC",
      },
      {
        name: "Headphones Bun",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURQAAANbW1v+ejv///8DAwP+JdRXwI4YAAAABdFJOUwBA5thmAAAA+ElEQVQ4y+3SQW6EMAwFUIcTYJTuOz9l35LOAehwganE/a9Sx8mEAIlG3XXRv30yjm2INQDYLsvM3AGvFJPI4cIcDJh2NMBPF60F3IQjYUCM2xHgPbZsZKVVg+ZAqNESW1XIzoHW74LS61lmGdx1XREmk75DLrNhTLcK6VutjhJJNzAKxbXIm8QeJGOJ3AviPlkkPpMRGreiIxVFKQXlIjY7eimL2tRTScB4r1NY2q3obzJ1etit6EhvH1ni3ZVwIpPJhTPeiknF4jbkh/l8ULoumRP1mehARC2iUxIR/Y6c/2qRjvxeo+4JVb+nX1x8ncj7lvznz+UHYi9JGo2FAEAAAAAASUVORK5CYII=",
      },
      {
        name: "Blue Frizzy",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1sDAwHTL01vAyTQqneIAAAABdFJOUwBA5thmAAABfklEQVQ4y3WUC5LDIAiG0ROI6QECswfojHuBTr3/mZaHyYq2TJo0fv6IgAFkqogsJg+xArfJKFbBF4IJCSMdq7SIAC9zBJ8QHk3t+QG1Yc8NtbaxjbQW0TGj54yO3977JjPU1d6rTMnjO+qO0NNyXB5vEV0Zw9pOgFRuxJpMHdeLRWIqJZLBkWW96imigV6E9c6yTnNUe0ceiZfUi5i8Olh/+kvnyahXhfW/IX6YiNHC1VJm9SDPio+X+5+bgnQKScgyyV+GiftTVWzxMgZkDmVJst1OTTHCsGWk2+Z+yR697Z8XxLaNz4i+Ix7I1ioRjeSwlqouiDxvTDF4RewIWTye88bYVrci8b4Yj8bhkCiN3lAy1XdEASU9pu5QtxHOo57iWxTPY9UtgwUYj2oaVRJXvB19K5PM0F/8YFg/GoLli2FTB0q7R0fF2fLJ8By6DwgxVrJHGbcQvU1NhqK/7N2c7CWISnYvelv8Qf4fWFSQT5wWntNR8tQPafF4wh8tc1GSDMUVRwAAAABJRU5ErkJggg==",
      },
      {
        name: "Blue Bun",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0BAMAAAA3VgbYAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAPUExURQAAANbW1nTL08DAwGDCzPS7kgkAAAABdFJOUwBA5thmAAAAwUlEQVQ4y+3S4Q2EIAwFYNiAJzfAHRtcmMAL+89kLUofoMkN4PthjF9aKOJQ8wVizvJ0FlAGY0p7Phe0pJr3RKekRBStW1dWd8dClPt21hFRi8pvLsM+C16lyLZ13aWVRaUipJuJ2rySnoAUFTsxLCfVfisRwmG1H2byWYtwSyv6ENlH3xMXjWQS3H8kZ7jy+p4og4uI3PEn0eYhqlMaeaJhUrFwvgwinyYKjcbrZte2kR+lv/buJt5Wme2enjy5yAY6lDFoIV2Q+QAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    25,
    [0, 1, 2],
    [
      {
        name: "Purple",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURQAAAJhur7SSxv///0kjdGUAAAABdFJOUwBA5thmAAAArElEQVQoz+3NsQ3CMBAF0EskmvTABDRMkREo8mPJ0i2QPkrLEu5pkOCYxw0jMATh20mkMAISrvx8979F/ufnzm6Nwq+1X6vQ53m+1SJb5xc1IoC/TNrgWzXV3iYdcEqyRY04YFIZANEIy6VVcEizLtccg0bm0OUaA2dA9ClYGt8Frm+Nq9U9C6xhj81i0B5vu2r6gfJZA1QGrrZmowXFwJnrGRxf3NGUiwxm4QPdbEuti4XmkQAAAABJRU5ErkJggg==",
      },
      {
        name: "Pink",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURQAAAP18fP+ejv///wWt+HwAAAABdFJOUwBA5thmAAAArElEQVQoz+3NsQ3CMBAF0EskmvTABDRMkREo8mPJ0i2QPkrLEu5pkOCYxw0jMATh20mkMAISrvx8979F/ufnzm6Nwq+1X6vQ53m+1SJb5xc1IoC/TNrgWzXV3iYdcEqyRY04YFIZANEIy6VVcEizLtccg0bm0OUaA2dA9ClYGt8Frm+Nq9U9C6xhj81i0B5vu2r6gfJZA1QGrrZmowXFwJnrGRxf3NGUiwxm4QPdbEuti4XmkQAAAABJRU5ErkJggg==",
      },
      {
        name: "Blue",
        png: "iVBORw0KGgoAAAANSUhEUgAAADQAAAA0AgMAAAC4FvN4AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURQAAAFirxnTL0////56gI+sAAAABdFJOUwBA5thmAAAArElEQVQoz+3NsQ3CMBAF0EskmvTABDRMkREo8mPJ0i2QPkrLEu5pkOCYxw0jMATh20mkMAISrvx8979F/ufnzm6Nwq+1X6vQ53m+1SJb5xc1IoC/TNrgWzXV3iYdcEqyRY04YFIZANEIy6VVcEizLtccg0bm0OUaA2dA9ClYGt8Frm+Nq9U9C6xhj81i0B5vu2r6gfJZA1QGrrZmowXFwJnrGRxf3NGUiwxm4QPdbEuti4XmkQAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    26,
    [0, 1, 2, 3],
    [
      {
        name: "Pants",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEw3bbclSqD6oxtQj6jDAAAAAXRSTlMAQObYZgAAADxJREFUeAFjGP5AA85aASJEgZgJzGJ1YGDgWgBmhYaGZoFZjKGxoasawKpDQ8NWQfSJhkYBJSEKs3BZAwBefwqRaPYXAAAAAABJRU5ErkJggg==",
      },
      {
        name: "Cheese",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEz/pwD1hB//wQCHSzU5AAAAAXRSTlMAQObYZgAAAEpJREFUeAFjGPyA/x+MtfpfA4TBtPr/BwiLcWn9HygrNPT/ARgr/AOEFTU1NADCylq6FAsLKsvANTV0AdSS0DAYixHOYmADsggAADGvGCBQMHTHAAAAAElFTkSuQmCC",
      },
      {
        name: "Bow",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEznNDTvYGDXERH84+WeAAAAAXRSTlMAQObYZgAAACVJREFUeAFjGD5AFAghINQh1AHCCs8qhbJEX11lQIgh1CH0UggAxWwHaRi4dDYAAAAASUVORK5CYII=",
      },
      {
        name: "Belly",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAACBJREFUeAFjGBRA/gCItH8AIus/IJE/0El7sLj8A1T9AL1FC3BSWV5FAAAAAElFTkSuQmCC",
      },
    ]
  );

  await trait.uploadTraits(
    27,
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [
      {
        name: "White Short Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEyamprT09Pu7u5ycnL+O0S0AAAAAXRSTlMAQObYZgAAAKZJREFUeAGNkNdxhUAMAEUoAFHBnfA/QQU49t8SaUdn++UlafaUBnkNS3xrM4sAZVn7MzJV40SJ6qwcWdY9OoxyVGNSmAM9wGhvqCuTMZIp+mtIOWCW1BiSUiwdphOwgkDJGXzCNIuBh3GPFHdS3EnyP8Zvm+GvGU6zq6ml80KfxT1hmjJrST+xYfCGkV/z83HP1H+L4G8KqB1oJ4XzL+a/pjpjlTts5sEr8HVIeeUAAAAASUVORK5CYII=",
      },
      {
        name: "White Long Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAElBMVEVHcEyVlZWrq6tfX187OzuDg4Nh2EOYAAAAAXRSTlMAQObYZgAAAK1JREFUeAGN0deRwzAMBFBQpwII4QqwMKNvBxTgWIH678WBCwZnr4MwT8yk38IRz8DMuQCx2DpVbMZ4Y6iCGF6x2LW6ieFVgMQst9gtLmsGPYlASLxTK2v2YC4KUkQsnhJxkVW/w/JLqKe7NoMuTkm60UWzqOYmqkk6VTTSRvS1DK3MSeY68oRxJtXos5e5xn9I4BIXqnLavZPQdkLaJojfxYpK0rlKK3+pNnqTC7agJzUEEq3QAAAAAElFTkSuQmCC",
      },
      {
        name: "Grey Short Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAElBMVEVHcEyVlZWrq6tfX187OzuDg4Nh2EOYAAAAAXRSTlMAQObYZgAAAKxJREFUeAGNkedxxCAYREF2AaxwAdLO6Lft+wq4WIH670WBBS6Hp8DOI4P7DASVHkAJUoj2nxLMoBpT8tFUhWhLWo2pysuEYlZsJZt/JO5NlHFLiVvzj4zmcj5WE1OTRaGaPydQyaK2adnJND0EiyFLE1JNSDXiheFj016aMZmR7L6T4qBxBjLINHWuPpxudoEfGYfKaffM+MtO4rKJyHfx5yrpXOOl+UrZ3BNm7nMkjfBFbiAAAAAASUVORK5CYII=",
      },
      {
        name: "Grey Long Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAElBMVEVHcEyVlZWrq6tfX187OzuDg4Nh2EOYAAAAAXRSTlMAQObYZgAAAK1JREFUeAGN0deRwzAMBFBQpwII4QqwMKNvBxTgWIH678WBCwZnr4MwT8yk38IRz8DMuQCx2DpVbMZ4Y6iCGF6x2LW6ieFVgMQst9gtLmsGPYlASLxTK2v2YC4KUkQsnhJxkVW/w/JLqKe7NoMuTkm60UWzqOYmqkk6VTTSRvS1DK3MSeY68oRxJtXos5e5xn9I4BIXqnLavZPQdkLaJojfxYpK0rlKK3+pNnqTC7agJzUEEq3QAAAAAElFTkSuQmCC",
      },
      {
        name: "Dark Grey Short Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwrKytWVlZBQUEaGhqkyiviAAAAAXRSTlMAQObYZgAAAKdJREFUeAGN0NURwzAQBFAZCsiNG/CcChBs/oP9t2RaC8LZgM9PLPNf4PnsAKSChCDDVkEEbBFWXRA2IchSrSJs6ig+yRpZs8sA0osEigkcVEvqAnAt01HYyadNJzkYJgv4XvpEHSmt3UWTqKYuquyiatmlEn0vsZa4yUJjz5kt57GqntLmtay/P50CR4opcj9/kq4exNRdGNnehbdDGRYItTRbLeZDZpYKNr1FTXLnAAAAAElFTkSuQmCC",
      },
      {
        name: "Dark Grey Long Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwrKytWVlZBQUEaGhqkyiviAAAAAXRSTlMAQObYZgAAAKlJREFUeAGN0NeRwzAMBFAoFCCMGrgBC2DA/V+w+2/JAcvovA6CHjPps2jAc1HVUoA08m6VMitaGNUSGU0a+VJdhdG0QEKRa/iaLLuC7iRCKGJQL6WLKtaiBYJO4WikVbb1F9uvoZWGPkm+jiazyyJFREoXEZNZBJ2kE3ksqZdkktrMDvM4kQCZ61ruG7JoTRZqcvx9Jks/COm7IGzvvFGN3WLsZbKa6UnOXjc5ZTwfr/gAAAAASUVORK5CYII=",
      },
      {
        name: "Brown Short Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcExWNiV+WztsTzU7IRe2GirYAAAAAXRSTlMAQObYZgAAAKdJREFUeAGN0NURwzAQBFAZCsiNG/CcChBs/oP9t2RaC8LZgM9PLPNf4PnsAKSChCDDVkEEbBFWXRA2IchSrSJs6ig+yRpZs8sA0osEigkcVEvqAnAt01HYyadNJzkYJgv4XvpEHSmt3UWTqKYuquyiatmlEn0vsZa4yUJjz5kt57GqntLmtay/P50CR4opcj9/kq4exNRdGNnehbdDGRYItTRbLeZDZpYKNr1FTXLnAAAAAElFTkSuQmCC",
      },
      {
        name: "Brown Long Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcExWNiV+WztsTzU7IRe2GirYAAAAAXRSTlMAQObYZgAAAKlJREFUeAGN0NeRwzAMBFAoFCCMGrgBC2DA/V+w+2/JAcvovA6CHjPps2jAc1HVUoA08m6VMitaGNUSGU0a+VJdhdG0QEKRa/iaLLuC7iRCKGJQL6WLKtaiBYJO4WikVbb1F9uvoZWGPkm+jiazyyJFREoXEZNZBJ2kE3ksqZdkktrMDvM4kQCZ61ruG7JoTRZqcvx9Jks/COm7IGzvvFGN3WLsZbKa6UnOXjc5ZTwfr/gAAAAASUVORK5CYII=",
      },
      {
        name: "Black Short Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwaGhoNDQ0rKysAAADugtCVAAAAAXRSTlMAQObYZgAAAKdJREFUeAGNkIcVwyAMREWcARBkAFsLuNwAqfuv5MI98dKT78K9L7r8h0a2QVU9UGmyriQ1U1aMKSRjSZOtaTPGUqCJbjZsg8Y6LbyaRCOJg+7N1oVwLQk07BR9025aIVoRUvtkDDTNqARuAO8CsAvATrgzeG/yvcnFrGrYF4WR84xApGnqWmO8+Q6dA41o5Xb6ZML9IHLfhZhuWCuVcovp3uxKNvnAAnNzIqSuFtY8AAAAAElFTkSuQmCC",
      },
      {
        name: "Black Long Tail",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwaGhoNDQ0rKysAAADugtCVAAAAAXRSTlMAQObYZgAAAKlJREFUeAGN0YWVxDAMBFD5kgIs+wpI1MCBCljsv6WAxrg8C9H7MZs+C3s8HTPnAsRBZqtYhPFGULkgeMVBtmoXwSsH8Vn2yJ4kM1vuJUAooFMrexMEc5GDoJG/GnGRaTxi+SU0Utcm6u/VZPhLollUcxNVk0EVjbQRfSyxlWgS68h/GOdP1UOGMtffN8RxSRKqcj0+E9d2QtomSLqLiUrsFEMrX1YLPckKO6AlTDdN7iQAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    28,
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    [
      {
        name: "Unammused Blush",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwAAAAAAADzR0f///+sBKGHAAAAAnRSTlMAA++anIIAAAAvSURBVHgBYxhZgMlJiUFFSQFZREmJQYmACIOSggCTEhKfmRlMGRiASCgTKj7iAQArVgNjcs2iFAAAAABJRU5ErkJggg==",
      },
      {
        name: "Unammused",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwAAAAAAAD///8LCPomAAAAAnRSTlMAA++anIIAAAAcSURBVHgBYxgMQG/BrgYIS2vBKgwWV4sWwxAAAMVSBqm4uSbRAAAAAElFTkSuQmCC",
      },
      {
        name: "Sus",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcEwAAAD///8W1S+BAAAAAXRSTlMAQObYZgAAABdJREFUeAFjGFxANCG0AcoKCHVgGEoAAJr9AkXtk9CgAAAAAElFTkSuQmCC",
      },
      {
        name: "Sad",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwAAAAAAAD///8LCPomAAAAAnRSTlMAA++anIIAAAAgSURBVHgBYxgMgGnBCiiLa8EqKEt7wa4GqFiLFsMQAADM8gVcmw4YKgAAAABJRU5ErkJggg==",
      },
      {
        name: "Happy",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcEwAAAD///8W1S+BAAAAAXRSTlMAQObYZgAAACBJREFUeAFjGDjA6iAKZUkGpDpAWKIBoVAWa0Aow5ACAEEkAw2NHJgIAAAAAElFTkSuQmCC",
      },
      {
        name: "Cute Blush",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwAAAAAAADzR0f///+sBKGHAAAAAnRSTlMAA++anIIAAAAzSURBVHgBYxjWQEmBgUkJWYDJSYlBBSiKJKKkxKCESwRhjgCKOczMYMrAAERCmVDxEQ8AvuADyQIfx8EAAAAASUVORK5CYII=",
      },
      {
        name: "Cute",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwAAAAAAAD///8LCPomAAAAAnRSTlMAA++anIIAAAAhSURBVHgBYxg4wNWgBWXpLdjVAGFpLViFweJq0WIYAgAAVhkHXQoPl58AAAAASUVORK5CYII=",
      },
      {
        name: "Crying",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwAAAAAAABv4O3///8mcc1YAAAAAnRSTlMAA++anIIAAAAtSURBVHgBYxhhgEmJQUkBRURJCYhQlKgoMaigKGI2UhAwVkLRZQAUxWb+KAAAJyICissBJXwAAAAASUVORK5CYII=",
      },
      {
        name: "Angry Blush",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhBAMAAAClyt9cAAAAD1BMVEVHcEwAAAAAAADzR0f///+sBKGHAAAAAnRSTlMAA++anIIAAAA4SURBVHgBYxjWQAGImZAFmJSAhJICsoiKEoOSE4qIElAESQ1YhwBQJwIwM4MpAwMQCWVCxUc8AAD8SQNBJ9pkdQAAAABJRU5ErkJggg==",
      },
      {
        name: "Angry",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwAAAAAAAD///8LCPomAAAAAnRSTlMAA++anIIAAAAmSURBVHgBYxg4wMHABGVpMXA1QFjaC9ZBWVoLVkFZXC1aDEMAAADNUAVkD/OMWgAAAABJRU5ErkJggg==",
      },
    ]
  );

  await trait.uploadTraits(
    33,
    [0, 1, 2, 3, 4, 5, 6, 7, 8],
    [
      {
        name: "Witch",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwtLDAcGx7///+t7glGAAAAAXRSTlMAQObYZgAAADZJREFUeAFjQAGMoQ5QFmtoCJQlGhoKY0XB1IVmYWFlw8z4/28V1IzQsFUNCBZENjQKKDsMAQBmsw27dzy9CgAAAABJRU5ErkJggg==",
      },
      {
        name: "Unammused Eyebrows",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABBJREFUeAFjoAhUfGAYFAAAvxYBac5q3tYAAAAASUVORK5CYII=",
      },
      {
        name: "Top Hat",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEwAAAD///80NDRC7/yLAAAAAXRSTlMAQObYZgAAACJJREFUeAFjwA4YQwNgrKt4WV8DMHQwrVoAZYmGhjKMGAAAhqoIEAsa9xUAAAAASUVORK5CYII=",
      },
      {
        name: "Surprised Eyebrows",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABVJREFUCNdjYCAPcDiASJEFDIMCAACHdgD9eb9rmgAAAABJRU5ErkJggg==",
      },
      {
        name: "Gnome",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcEzoNzd+Hh7ioHMUAAAAAXRSTlMAQObYZgAAACZJREFUeAFjQAGscJZoAyYrdAEeFmPoChgrDM7KgrEYVgHVDW8AAI0pCGmW6sH7AAAAAElFTkSuQmCC",
      },
      {
        name: "Flower",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAADFBMVEVHcEz/mZlJrFz60xuMHnxVAAAAAXRSTlMAQObYZgAAABZJREFUeAFjwAFE4SxZLGIcWFkjGwAAbFIAYJIIShYAAAAASUVORK5CYII=",
      },
      {
        name: "Bow",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcEz/mZnvYGBkANRyAAAAAXRSTlMAQObYZgAAACVJREFUeAFjIAeIAiEEhDqEOkBYYVmpUJboqqkMCDGEOoTeYQkAgUoGx3rvGGwAAAAASUVORK5CYII=",
      },
      {
        name: "Baseball Hat",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcExCrEwnii2JX0s3AAAAAXRSTlMAQObYZgAAAC9JREFUeAFjwAFCA6AMxtAQKIs1NAzOisLCyoKyuFatgrJE4XpDYSzGUKDJwxIAAEHqCEFJLQ7dAAAAAElFTkSuQmCC",
      },
      {
        name: "Angry Eyebrows",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABNJREFUeAFjoAhwOIBIlgaGAQYAaU4AzYjdD0EAAAAASUVORK5CYII=",
      },
    ]
  );

  await trait.uploadTraits(
    35,
    [0, 1, 2, 3, 4],
    [
      {
        name: "Whiskers Mouth",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAgMAAAAqiir8AAAACVBMVEVHcEz///8AAADmzmMiAAAAAXRSTlMAQObYZgAAABxJREFUeAFjGJqAlUEExuSAMRiVBKAsFiCkOwAAMGgAXSE7idYAAAAASUVORK5CYII=",
      },
      {
        name: "Whiskers",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAABhJREFUCNdjYKAnMEhAsAUcQKSCAjXMBQBaxgEhNpfIrQAAAABJRU5ErkJggg==",
      },
      {
        name: "Teeth",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEz///+flKJDAAAAAXRSTlMAQObYZgAAABBJREFUeAFjGADA2wAlqQYAVswBG1cOhDIAAAAASUVORK5CYII=",
      },
      {
        name: "Happy",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYKA/EHIAkbwN1DMRAEQmAOCHLn/8AAAAAElFTkSuQmCC",
      },
      {
        name: "Default",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEwAAACfKoRRAAAAAXRSTlMAQObYZgAAABFJREFUeAFjGADABMbMVDQRAALqAAjVkl7LAAAAAElFTkSuQmCC",
      },
    ]
  );

  await trait.uploadTraits(
    36,
    [0, 1],
    [
      {
        name: "Small",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEz/mZkI4qoPAAAAAXRSTlMAQObYZgAAAA5JREFUeAFjoBNgoqnpAAGCAAN91w3/AAAAAElFTkSuQmCC",
      },
      {
        name: "Big",
        png: "iVBORw0KGgoAAAANSUhEUgAAACEAAAAhAQMAAABtKlAsAAAABlBMVEVHcEz/mZkI4qoPAAAAAXRSTlMAQObYZgAAABRJREFUeAFjoDlgAZN8YJKNRnYAAAmKABlTDp6xAAAAAElFTkSuQmCC",
      },
    ]
  );

  await houseTrait.uploadTraits(
    0,
    [0],
    [
      {
        name: "Shack",
        png: "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAQlBMVEVGOC2Hcl8vMDwlIikwJh89Pk4jHBcjICVfSTczLjhJOCo7MCd9ZE9uV0MzKSFYUF2Ni42YlJVqXF9iXXCuo5uHdXShCQpUAAACo0lEQVR4AZWXiZKDIBAFR8UDDQvm+P9fXQaeZhwhpb0nlt0BSvYge4fVnqDbfj3gLSiM61Ddv9DwCGh/veIDBMbE7l8AFgIjuOkzCGzccAEdh/d8BEZBfbsFqzQI/sYVXygBgXJiPfnZscIfaTyhfWn7EcBHQPHT15l6QPugEAhjiQs+AvDPK6z7Esq+x6dqoAodfAIjw7v41gFK6IDfBoJ5JSLbCp8EMiCgxTm3UCL64EmKaoCIlmXZnWfFn9d6AMBZpshCEp7j2/lY8PpRhj8Mg/HGmHx3hBTLmq7BRwA+CiZB4DQZTBB+IWB0oDyZXbs0AUTeck+qgUH7GMppyID2mbzdkUUHJYfAuu0NfLxcGgcU9mghEOAXNn0Ig/FqDQAB+AsUdecchsGrpgowcCpP/yybMrUHqAJKGqQQCPXA3xE68V3CUMSb36jTONzDn46zAd5cAb46TCZu73O6gHlSJfDIFK3HzmQIXtgDngtmnp9zphCYv8QAfBWYqhwXdwzAR6A6+w+WhsBpDxBo3EbTyNljbbtfCzRN85dpCIUTvwOEQhNxRfuNFZQDjkWK8BdX8VUgjBsrGccvDR+Bp/Y50Pd74OsH4sBf4xz7CDw+6kFKgT5yWkIYc8A5rIMDcfMfG3MmTeCFQkgBgAClAD23Jcwb7wkYYr9PfimABXDgqVePQM+wXwyw73JA+aDPQDoGJpefAPdO/vlswn8dAhh8A+Te/GkGR7+Fv0lj2+4jPElE6+k5egAOADitDJART6IT4jQD3P4jQPEscOBDDQfUMlqmBy+WSFxKm4DTWDmLLXhhJxE4FsD0KwD/G0Chi0ygywTfSXA7BGstySvWdl2zY62P4B8W+P71enVdvLKuNkMd4AEmAKwkzwa3SkjYwN7iH8X5aIoUD5xSAAAAAElFTkSuQmCC",
      },
    ]
  );

  await houseTrait.uploadTraits(
    1,
    [0],
    [
      {
        name: "Ranch",
        png: "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAALVBMVEX/7rKRoID///92dHLL7v5chH1+npn+4HVzhl7v7+/KlXGcmZapeVn+55X+11L/6PpcAAACaklEQVR4Ab3QNXAbQRQG4A0zrINNaEcUBpWucl67n/GsetM1Ya7VqcyY3U9IkyoMfapQlyrYz/Vl3v/2nvQuMlX5DYL95n9vz/gV8l+Ac8uDxC0p6KTkjeOXxZLg6F+QSBsdOaRkigWuJBAR4MXoAg3AiyDpBaVeUEk7SyoQX+N5CpGDFATAdUBKGSWQxA/jniMOBQgBTxlKlVATUKEA/WMQzyeKAGEV70FYA3wQEcGQgHFv8Gmi0QGuJKAhALODAJdPIBBICFDCpwwoIQQFVMZl5wAPIAt0S1QASEouf2y3AVRWAYIe8fHjh1R2WBy0H6ay9kQEg0FG1FUuFAB3TAzXJf3P666CZxl4RAQh1Ovvn3cK3El+VAICPVgukLiqe8VDGnxNTmEDZ26iIg0AgwEZlvFccNRsci/jlgBSIFtQgaGKEBTQG6DAoELAIhuYWNEQ0FOw4/v379/cywi8KsCWKJCKCHxPQcwmVEQQL6A3kIoQAAZQ3Sk4/Z3yNa+IYJErSAWDgf7ni2wgFUYXvJcrqAqDDRYtQMoODcm9bm4eXesoxuCFQMjBTYdUGfjETxJYWJg037tgAalm2R8CJQByk7Hh4t4ky25Ok/NVGcGglANrk3s3+giUcvDx40cAMAE3rJ3s7tBuP5URa+w+gL6mtbFBgIyw1gK0COylFfyZTMD372u97wJLLXrEdmrAZ0vZxwCha86pEVvos0UIHMQMe+AeIoCy2UZAh63WIoC/BMDrQVTYAtjMgL6PksHhjB+1oxwFaNqDCiCxYYFyHwBhAKHAZKxoxQCI6HOcBWTS1fi8CQCxeHDwF3RHLYgEG+npAAAAAElFTkSuQmCC",
      },
    ]
  );

  await houseTrait.uploadTraits(
    2,
    [0],
    [
      {
        name: "Mansion",
        png: "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAMAAACdt4HsAAAAQlBMVEXws6P38ubvpphaZnzAm9ixhM/45drupJb79v1CTV/yxrDB/f/lwe8vOEd3f26RoID24cXo4erMxs6c3vyRlKNxutscveT3AAACmUlEQVR4AeWU62LbIAyFE2OzozCv8Uje/1UnS1DFCuotP/flBinnKyC1p18v8j8IEj9eElg+EExCn059avPkf27zM/P5EVKwhbOiO4hJ8hhw7oJPSacRmpYjTB8+9Ajuu4n3b4JPIKLR+b3A7G5KlBLZvJEfBEeevuI40cmRczbB4GYng4h2w3Qk73SBMdjVnoffQ1aaw+e9IKHsBp82xyd5WlmwUkrH8CZP4dQKm8/Gs4DI4g7b2LOBRAAR0CnG5N6xGC4xubhhLhHMHTV+Cyc4vyz4moGMdV0fBHrjMZPlk4bXoyDIOQm11mW6AMLXBC1fkDSvgsIEgiBfzKACfEUw9fsTATHvAkQ7mPTqLg1Kcnsi0OHhCGQ4T8/30gFYkxq8ICWvMFqc0ZWqIBP0uDou9pt9Xtfdbs3wXkZSEpLfhOVFQQLH2bELOkRWZN2Nu4NVaXFKirUiHYqsSLAL5nXAYgI90cqCtknZxbtg3+vC9MBvYf/K34GIDBUQxYJehWVAPwJ9IoAK5kdk5eVyvV73HQAXxAIUL+jLdAcmAND+flkAQAUhA0GB9q4IShfwHDN4NPd3faILriy4PgoQCCzdBLYDxgR43EEFYDuIBeERiGoK+YKAiO7FErfbYcgGKSOYcRWIqNZK9966DRtrH4SNRMxWtkrkokbOXIWPWrlu962WhQEWxUZAZgHvAogEtTHPnwiuGArqtm218FtRgb0BXjC8xPs832q5LXMToBTtABl4gS/jzwV4FtQuQBcgFFgrF769UkrVpwjQdwC3gzw4wuaIjpAjAf4ewMeC4B9KT7c+AKMCwAQZO+NG4ktklrkJ9oEI9pEJaOczAZhFaCMdqCBma1AEC/58gF1hsODt7e10mBl+Xcg/435j9hl47L0AAAAASUVORK5CYII=",
      },
    ]
  );
}

upload();